name: Test Padelspot

on:
  workflow_dispatch:

jobs:
  tester:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Installer les librairies
        run: pip install requests

      - name: Lancer le test
        run: python -u test_padelspot.py
